### ISSUE TITLE
if statement break syntax highlighting

### ISSUE THREAD

**Issue by stefan7018** [atom/language-shellscript#22] opened 2015-09-29 13:44 UTC
Hello,
using Atom 1.0.19, Windows 7 x64 and language-shellscript 0.17.0.
See the picture below for more information.

![ifstatement](https://cloud.githubusercontent.com/assets/14890242/10165593/68327e7e-66c0-11e5-9cbe-2ce92f49001d.PNG)

Regards,
Stefan

**Comment by 50Wliu** [comment] 2015-09-29 13:47
Duplicate of #21, please subscribe there for updates

**Closed by 50Wliu** 2015-09-29 13:47 UTC
