### ISSUE TITLE
Syntax highlight breaks when Bash heredocument delimiter is indented 

### ISSUE THREAD

**Issue by aeschli** [atom/language-shellscript#100] opened 2018-01-29 08:02 UTC
_From @benqzq on December 29, 2017 23:17_

Syntax highlight breaks when Bash heredocument delimiter is indented:

### Indented

![indented](https://user-images.githubusercontent.com/31392185/34449232-deaccb6a-ecfe-11e7-978c-15731cc2e29f.PNG)

### Not indented

![not indented](https://user-images.githubusercontent.com/31392185/34449234-e6c5655a-ecfe-11e7-8ef2-2519c0378b29.PNG)

## Why this phenomenon shouldn't happen

Bash functions (and even external heredocuments) tgnore/trim out, all indentations.

Hence, indenting a delimiter shouldn't effect syntax highlight, IMHO.

_Copied from original issue: Microsoft/vscode#40956_

**Comment by aeschli** [comment] 2018-01-29 08:02
@benqzq Can you attach a (complete) sample that shows the problem?

**Comment by aeschli** [comment] 2018-01-29 08:02
_From @benqzq on January 11, 2018 10:53_

https://github.com/benqzq/system/blob/master/wsla.sh

**Comment by aeschli** [comment] 2018-01-29 08:02
@benqzq I get a 404 when accessing the link

**Comment by aeschli** [comment] 2018-01-29 08:02
_From @benqzq on January 26, 2018 17:9_

@aeschli I fixed the link.

**Comment by 50Wliu** [comment] 2018-01-29 22:05
According to https://tldp.org/LDP/abs/html/here-docs.html, the delimiter _must_ start at the first character of a line, _except_ when the heredoc uses `<<-`.

As that's the case here I'll label this as a bug.

**Comment by 50Wliu** [comment] 2018-02-11 05:25
The provided file does not reproduce the bug.  Marking as `more-information-needed`.
![tab-heredoc](https://user-images.githubusercontent.com/2766036/36070091-092a0f94-0ec2-11e8-9cde-a0b523df6cc0.png)

**Comment by aeschli** [comment] 2018-02-12 08:54
@benqzq The provided file does not reproduce the bug. Indenting `AWSM` also doesn't make a difference.

**Comment by ChujunGeng** [comment] 2018-02-22 00:08
I have a similar problem. Syntax highlighting is totally broken by heredoc, which in my case is an awk script. Here's the link to my file: [gradersLittleHelper/checkStat.sh](https://github.com/ChujunGeng/gradersLittleHelper/blob/master/checkStat.sh)

**Comment by 50Wliu** [comment] 2018-02-22 02:02
@ChujunGeng your file looks fine to me, which means you should ask github/linguist to update the language-shellscript grammar.

**Comment by 50Wliu** [comment] 2018-02-22 02:02
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/language-shellscript/issues/100#issuecomment-364722856. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by 50Wliu** 2018-02-22 02:02 UTC
Labels: more-information-needed, needs-reproduction

**Comment by ChujunGeng** [comment] 2018-02-22 03:17
Have you actually opened my file inside Atom? The syntax highlighting is completely broken just like how it looks on GitHub. By contrast, it's compatible with Vim's syntax highlighting.

**Comment by 50Wliu** [comment] 2018-02-22 04:31
Yes, I have.
![quoted-here-document](https://user-images.githubusercontent.com/2766036/36520488-39254aa6-175f-11e8-846a-be35d943f03d.png)

This will be fixed in a future Atom release.

**Comment by ChujunGeng** [comment] 2018-02-22 04:32
Awesome! Thanks for your quick response.

**Comment by astorath** [comment] 2018-09-05 08:29
@50Wliu, can you clarify in what release actually? The issue is still present on atom, atom-beta and vscode...

**Comment by mk-pmb** [comment] 2019-07-19 15:38
I still have this issue in VSCode 1.36.1 with this bash script. Can someone please check whether it's an atom problem, or to which atom version VSCode should upgrade?

```bash
#!/bin/bash
nl <(sed -nre 's!^\s+!!p' <<'  __FOO__'
  ########################
  ## Dummy Message      ##
  ########################
  __FOO__
  )
echo bar
```

Screenshot: https://abload.de/img/heredocigjr2.jpeg

**Comment by Arcanemagus** [comment] 2019-07-19 15:59
@mk-pmb VSCode is still using the old TextMate grammar, which the Atom team no longer maintains as we have moved many grammars (including this one) over to Tree-sitter. If one of the VSCode team would like to take over maintenance of the TextMate grammar they should contact the Atom team about it 😉.

There are several extensions that add Tree-sitter parsers to VSCode, with [vscode-tree-sitter](https://github.com/georgewfraser/vscode-tree-sitter) being one of them, however it looks like that one in particular hasn't added shell script support yet.

**Comment by mk-pmb** [comment] 2019-07-19 16:32
Thanks!
