### ISSUE TITLE
Nested Single Quotes breaks Shell Syntax Highlighting

### ISSUE THREAD

**Issue by bengtbrodersen0042** [atom/language-shellscript#147] opened 2019-06-27 14:57 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Following code is not highlighted correctly, it is because of the the escaped `\'` within single quotes. This is a legal shell syntax because the single quoted string is prefixed with a `$`
`echo $'aa\'bb'`

### Steps to Reproduce

Paste `echo $'x\'x'` in Atom editor wind with enabled shell syntax highlighting

**Expected behavior:**

Proper syntax highlighting

**Actual behavior:**

Broken syntax highlighting after nested single quote

**Reproduces how often:**

100%

### Versions

1.38.2

**Comment by rsese** [comment] 2019-06-28 20:03
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/language-shellscript/issues/146 so you can subscribe there for updates if you'd like.

If I'm misunderstanding and you think this is a different issue, please let me know.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-28 20:03 UTC
