### ISSUE TITLE
Unix -opening and closing for `` is not getting detected properly

### ISSUE THREAD

**Issue by aeschli** [atom/language-shellscript#109] opened 2018-02-16 14:00 UTC
_From @ethic123 on February 13, 2018 12:36_

### Issue Type
Bug

### Description

In Unix Script, Create a sqlplus session using ``. You will see that it is detecting the opening grave (accent) not the closing one.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 10.0.14393

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.24
python|ms-|2018.1.0

</details>
Reproduces without extensions

_Copied from original issue: Microsoft/vscode#43582_

**Comment by aeschli** [comment] 2018-02-16 14:00
_From @egamma on February 13, 2018 14:14_

@ethic123 please provide a snippet that illustrates the problem.

**Comment by aeschli** [comment] 2018-02-16 14:00
_From @ethic123 on February 13, 2018 14:32_

Please try below snippet in VSCode
![image](https://user-images.githubusercontent.com/13498501/36154853-b66f754e-10f8-11e8-80f7-be6f39228613.png)

```sh
echo $abc

abc=`sqlplus -S $user/$password@"$tns" <<-EOF
        SET ECHO OFF;
        SET HEADING OFF;
        SET PAGESIZE 0;
        SET TERMOUT OFF;
        SET SERVEROUTPUT ON;
        SELECT 1 FROM DUAL;
        exit;
		EOF`

echo $abc
```

**Comment by 50Wliu** [comment] 2018-02-16 15:09
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #86. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2018-02-16 15:09 UTC
