### ISSUE TITLE
[bash] Variable is not highlighted in heredoc

### ISSUE THREAD

**Issue by alexr00** [atom/language-shellscript#151] opened 2019-09-04 10:10 UTC
From @Ash258 in https://github.com/microsoft/vscode/issues/80270

```bash
#!/bin/bash
variable='whatever'
cat << END
<prtg>
	<result>
		<Channel>Memory usage</Channel>
		<Value>$variable</Value>
	</result>
</prtg>
echo "$variable"
END
```

Variable substitution is supported inside heredoc and variables should be highlighted as in normal string.

![image](https://user-images.githubusercontent.com/13260377/64189738-2cd28380-ce75-11e9-84c7-8c2ae0918d93.png)

![image](https://user-images.githubusercontent.com/13260377/64189631-f1d05000-ce74-11e9-8097-be76e9db044c.png)

Bat output for comparison:

![image](https://user-images.githubusercontent.com/13260377/64198350-5ea11580-ce88-11e9-8c97-01dab25aa9b8.png)

**Comment by rsese** [comment] 2019-09-04 20:16
Thanks for the report!

> Variable substitution is supported inside heredoc and variables should be highlighted as in normal string.

Looks like this works in Atom 1.40.1 on macOS 10.14.6 with Tree-sitter enabled:

![bash-heredoc-variable](https://user-images.githubusercontent.com/734194/64288071-c5750c00-cf26-11e9-95a9-209051e91801.png)

Since the problem isn't an issue with Tree-sitter, we'll go ahead and close as described below.

---

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.

**Closed by rsese** 2019-09-04 20:16 UTC
