### ISSUE TITLE
Square brackets in quotes

### ISSUE THREAD

**Issue by alexr00** [atom/language-shellscript#152] opened 2019-10-10 07:51 UTC
Originally from @jkmik244752 in https://github.com/microsoft/vscode/issues/66409

The following is a valid shell code snippet that currently breaks syntax highlighting.
```
${my_array[$(myprogram ']')]}
```
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-36-generic

**Comment by rsese** [comment] 2019-10-10 21:07
Thanks for reporting - this doesn't seem like an issue (or the issue is not the same at least) with Tree-sitter but let me know if I'm misunderstanding.  Atom 1.42.0-nightly8 on macOS 10.14.6 with Tree-sitter disabled:

![firstmate-shell](https://user-images.githubusercontent.com/734194/66606222-3edfca00-eb77-11e9-9bd2-c9c28c2fc563.png)

Using Tree-sitter:

![tree-sitter-shell](https://user-images.githubusercontent.com/734194/66606236-430be780-eb77-11e9-86dd-acf5fdd9b59a.png)

---

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.

**Closed by rsese** 2019-10-10 21:07 UTC
