### ISSUE TITLE
commands following heredoc delimiter are formatted as string

### ISSUE THREAD

**Issue by allgoewer** [atom/language-shellscript#117] opened 2018-07-03 09:27 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Syntax highlighting is broken for commands following the heredoc delimiter (formatted as string)

![image](https://user-images.githubusercontent.com/6408150/42211173-32f326ce-7eb3-11e8-92de-759e2f9dde0c.png)

### Steps to Reproduce

1. Paste the following snippet
```
cat <<EOF | wc -c
test
123
EOF
```

2. Set grammar to "Shell Script"

### Versions
```
$ atom --version

Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by Arcanemagus** [comment] 2018-10-10 18:11
I'm unable to reproduce this with this text in Atom v1.33.0-nightly9:
```sh
cat <<EOF | wc -c
test
123
EOF

echo "Am I a string?"
```

TextMate:
![image](https://user-images.githubusercontent.com/427137/46756818-319ab180-cc7d-11e8-92d0-687e762139e5.png)

Tree-sitter:
![image](https://user-images.githubusercontent.com/427137/46756808-28a9e000-cc7d-11e8-9e1e-d02826d3cd46.png)

Since it looks like this has been fixed in the time since this was filed, I'm going to go ahead and close it. Thanks for reporting this!

**Closed by Arcanemagus** 2018-10-10 18:11 UTC
